config/routes.rb
Rails.application.routes.draw do
  get 'works/index'

  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'

  get 'home/index'
  get 'home/about'
  
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX ,:message => 'メールアドレスを入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
    render :action => "index"
  end

  def confirm
    params.permit!
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      render :action => "confirm"
    else
      render :action => "index"
    end
  end

  def thanks
    params.permit!
    @contact = Contact.new(params[:contact])
    ContactMailer.received_email(@contact).deliver

    render :action => "thanks"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/contact/confirm.html.erb
<div class="bg-img">
  <div class="bg-mask py-5">
    <%= form_for @contact, :url => contact_thanks_path do |f| %>
      <div class="container">

        <div class="text-center">
          <h4 class="font-weight-bold">こちらの内容を送信します。<br>
            送信ボタンを押してください。</h4>
        </div>

        <div class="form-group mt-5">
          <label class="font-weight-bold">名前（必須）</label>
          <%= f.text_field :name, class: "form-control",
            value: @contact.name, readonly: true %>
        </div>

        <div class="form-group">
          <label class="font-weight-bold">メールアドレス（必須）</label>
          <%= f.text_field :email, class: "form-control",
            value: @contact.email, readonly: true %>
        </div>

        <div class="form-group">
          <label class="font-weight-bold">お問い合わせ内容</label>
          <%= f.text_area :message, class: "form-control",
            value: @contact.message, rows: 5, readonly: true %>
        </div>

        <div class="text-center">
          <%= f.submit '送信', class: "btn btn-primary" %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/contact/index.html.erb
<div class="bg-img">
  <div class="bg-mask py-5">
    <%= form_for @contact, :url => contact_confirm_path do |f| %>
      <% if @contact.errors.any? %>
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @contact.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
      <% end %>

      <div class="container bg-default">
        <div class="form-group">
          <label class="font-weight-bold">名前（必須）</label>
          <%= f.text_field :name, class: "form-control", placeholder:"名前" %>
        </div>

        <div class="form-group">
          <label class="font-weight-bold">メールアドレス（必須）</label>
          <%= f.text_field :email, class: "form-control", placeholder:"メールアドレス" %>
        </div>

        <div class="form-group">
          <label class="font-weight-bold">お問い合わせ内容</label>
          <%= f.text_area :message, class: "form-control",
          placeholder:"なんでも書いてね！", rows: 5 %>
        </div>

        <div class="text-center">
          <%= f.submit '確認', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contact/thanks.html.erb
<div class="bg-img">
  <div class="bg-mask">
    <div class="container text-center py-4 my-auto">
      <h3 class="py-4 font-weight-bold">お問い合わせいただきありがとうございました。</h3>
      <%= link_to "HOMEへ", home_index_path, class:"btn btn-primary"%>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="bg-img1">
  <div class="container">
    <p>I Programmer</p>
    <span>将来はフルスタックエンジニアに</span>
  </div>
</div>
<div class="bg-img2">
  <div class="container">
    <p>My hobby sleep</p>
    <span>最近の睡眠時間3時間だけど寝るの好き</span>
  </div>
</div>
<div class="bg-img3">
  <div class="container">
    <p>I like cats</p>
    <span>ネコ一匹飼ってる</span>
  </div>
</div>

app/views/home/index.html.erb
<div class="container bg-light mt-4">
  <div class="row align-items-center">
    <div class="col-6 text-center">
      <h4 class="mt-3">高専生エンジニア</h4>
      <h1 class="mt-3">96nekoR</h1>
      <p class="text-justify mt-4">
        プログラミング学習サイトを利用して勉強中。2016年と2017年のプログラミングコンテストに出場。
        気軽に<%= link_to "Twitter", "https://twitter.com/fps_seed" %>フォローしてください！
      </p>
    </div>
    <div class="col-6">
      <%= image_tag "neko.png", :class => "img-fluid" %>
    </div>
  </div>
  <p class="text-center mt-5">Made by 96nekoR</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <nav class="navbar navbar-light bg-light">
      <div class="float-left">
        <%= link_to (image_tag "icons8-reading-64.png", :size => "50x50"), home_index_path %>
      </div>
      <div class="float-right">
        <ul class="nav">
          <li class="nav-item pr-4"><%= link_to "紹介", home_about_path %></li>
          <li class="nav-item pr-4"><%= link_to "ブログ", works_index_path %></li>
          <li class="nav-item pr-4"><%= link_to "連絡先", contact_path %></li>
        </ul>
      </div>
    </nav>
  </header>

  <%= yield %>
</body>
</html>

app/views/works/index.html.erb
<h1>Works#index</h1>
<p>Find me in app/views/works/index.html.erb</p>